app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from . import main
from flask import render_template, request, redirect, url_for
from ..models import ArticleCategory, Article, ProductInformation, Category, IndustryIndex
from sqlalchemy import and_, or_
from ..util import data
from ..database import db_session

@main.route('/')
def index():
	activeid = 0

	categorylist = Category.query.limit(3)

	c = categorylist[0]
	dongli_huadong = c.productInformation.filter_by(dpareaid=1).order_by(ProductInformation.rldate.desc()).limit(15)
	dongli_huadong = [p.to_brief_json() for p in dongli_huadong]

	c = categorylist[0]
	dongli_huabei = c.productInformation.filter_by(dpareaid=2).order_by(ProductInformation.rldate.desc()).limit(15)
	dongli_huabei = [p.to_brief_json() for p in dongli_huabei]

	c = categorylist[0]
	dongli_huanan = c.productInformation.filter_by(dpareaid=7).order_by(ProductInformation.rldate.desc()).limit(15)
	dongli_huanan = [p.to_brief_json() for p in dongli_huanan]

	c = categorylist[0]
	dplist = [3, 4, 5, 6, 8]
	filter_result = reduce(or_, [ProductInformation.dpareaid == i for i in dplist])

	dongli_other = c.productInformation.filter(filter_result).order_by(ProductInformation.rldate.desc()).limit(15)
	dongli_other = [p.to_brief_json() for p in dongli_other]

	c = categorylist[1]
	wuyan_all = c.productInformation.order_by(ProductInformation.rldate.desc()).limit(15)
	wuyan_all = [p.to_brief_json() for p in wuyan_all]

	c = categorylist[2]
	lianjiao_all = c.productInformation.order_by(ProductInformation.rldate.desc()).limit(15)
	lianjiao_all = [p.to_brief_json() for p in lianjiao_all]

	article = Article.query.order_by(Article.hits.desc()).limit(10)

	dongli_chandi = data.main_chandi(1)
	dongli_qnet = data.main_Qnet(1)
	dongli_st = data.main_St(1)
	dongli_mt = data.main_Mt(1)

	wuyan_chandi = data.main_chandi(3)
	wuyan_qnet = data.main_Qnet(3)
	wuyan_st = data.main_St(3)
	wuyan_mt = data.main_Mt(3)

	lianjiao_chandi = data.main_chandi(2)
	lianjiao_qnet = data.main_Qnet(2)
	lianjiao_st = data.main_St(2)
	lianjiao_mt = data.main_Mt(2)

	return render_template('main.html', activeid=activeid, dongli_huadong=dongli_huadong,
				dongli_huabei=dongli_huabei, dongli_huanan=dongli_huanan, dongli_other=dongli_other,
				wuyan_all=wuyan_all, lianjiao_all=lianjiao_all, article=article,
				dongli_chandi=dongli_chandi, dongli_qnet=dongli_qnet, dongli_st=dongli_st, dongli_mt=dongli_mt,
				wuyan_chandi=wuyan_chandi, wuyan_qnet=wuyan_qnet, wuyan_st=wuyan_st, wuyan_mt=wuyan_mt,
				lianjiao_chandi=lianjiao_chandi, lianjiao_qnet=lianjiao_qnet, lianjiao_st=lianjiao_st, lianjiao_mt=lianjiao_mt)

@main.route('/stock')
def stock():
	activeid = 1

	page = request.args.get('page', 1, type=int)
	count = request.args.get('count', 20, type=int)
	
	category = Category.query.all()
	product = ProductInformation.query.filter_by(typeid = 1).order_by(ProductInformation.rldate.desc()).all()

	product_raw_all_filter = [ProductInformation.typeid == 1]
	#fen lei filter
	fenlei_query_string = request.args.get('fenlei', '', type=str)
	if fenlei_query_string != '':
		fenlei_list = fenlei_query_string.split(',')
		fenlei_filter = reduce(or_, [ProductInformation.ctgid == int(i) for i in fenlei_list])
		product_raw_all_filter.append(fenlei_filter)
	else:
		fenlei_query_string = None

	#chan di filter
	chandi_query_string = request.args.get('chandi', '', type=str)
	if chandi_query_string != '':
		chandi_list = chandi_query_string.split(',')
		chandi_filter = reduce(or_, [ProductInformation.pdpid == int(i) for i in chandi_list])
		product_raw_all_filter.append(chandi_filter)
	else:
		chandi_query_string = None

	#jiaogedi filter
	jiaogedi_query_string = request.args.get('jiaogedi', '', type=str)
	if jiaogedi_query_string != '':
		jiaogedi_list = jiaogedi_query_string.split(',')
		jiaogedi_filter = reduce(or_, [ProductInformation.dpareaid == int(i) for i in jiaogedi_list])
		product_raw_all_filter.append(jiaogedi_filter)
	else:
		jiaogedi_query_string = None

	#join query
	industryIndex_raw_all_filter = [ProductInformation.indid == IndustryIndex.id]
	#Qnet filter
	Qnet_query_string = request.args.get('Qnet', '', type=str)
	if Qnet_query_string != '':
		Qnet_list = Qnet_query_string.split(',')
		Qnet_filter = reduce(or_, [data.Qnet_filter(int(id)) for id in Qnet_list])
		industryIndex_raw_all_filter.append(Qnet_filter)
	else:
		Qnet_query_string = None

	#St filter
	St_query_string = request.args.get('St', '', type=str)
	if St_query_string != '':
		St_list = St_query_string.split(',')
		St_filter = reduce(or_, [data.St_filter(int(id)) for id in St_list])
		industryIndex_raw_all_filter.append(St_filter)
	else:
		St_query_string = None

	#V filter
	V_query_string = request.args.get('V', '', type=str)
	if V_query_string != '':
		V_list = V_query_string.split(',')
		V_filter = reduce(or_, [data.V_filter(int(id)) for id in V_list])
		industryIndex_raw_all_filter.append(V_filter)
	else:
		V_query_string = None

	#Mt filter
	Mt_query_string = request.args.get('Mt', '', type=str)
	if Mt_query_string != '':
		Mt_list = Mt_query_string.split(',')
		Mt_filter = reduce(or_, [data.Mt_filter(int(id)) for id in Mt_list])
		industryIndex_raw_all_filter.append(Mt_filter)
	else:
		Mt_query_string = None

	product_all_filter = reduce(and_, product_raw_all_filter)
	industryIndex_all_filter = reduce(and_, industryIndex_raw_all_filter)

	pagination = data.Pagination(ProductInformation.query.join(IndustryIndex, industryIndex_all_filter).filter(product_all_filter).order_by(ProductInformation.rldate.desc()),\
				page, count)
	product = pagination.items

	producingArea = data.getStockProducingArea()
	jiaogeArea = data.getStockJiaogeArea()

	Qnet = data.getStockQnet()
	St = data.getStockSt()
	V = data.getStockV()
	Mt = data.getStockMt()
	
	return render_template('stock.html', activeid=activeid, category=category,
		product=product, producingArea=producingArea, 
		jiaogeArea=jiaogeArea, Qnet=Qnet, St=St,
		V=V, Mt=Mt, pagination=pagination, count=count, fenlei_query_string=fenlei_query_string, chandi_query_string=chandi_query_string,
		jiaogedi_query_string=jiaogedi_query_string, Qnet_query_string=Qnet_query_string,
		St_query_string=St_query_string, V_query_string=V_query_string, Mt_query_string=Mt_query_string)

	
@main.route('/purchase')
def purchase():
	activeid = 2
	page = request.args.get('page', 1, type=int)
	count = request.args.get('count', 6, type=int)
	pagination = data.Pagination(ProductInformation.query.filter_by( typeid = 0).order_by(ProductInformation.rldate.desc()), page, count)
	product = pagination.items
	return render_template('purchase.html', activeid=activeid, product=product,
				 count=count, pagination=pagination)


@main.route('/logistics')
def logistics():
	activeid = 3
	return render_template('logistics.html', activeid=activeid)

@main.route('/spot_quotation')
def spot_quotation():
	activeid = 4
	actgid = request.args.get('type', 1, type=int)

	page = request.args.get('page', 1, type=int)
	count = request.args.get('count', 20, type=int)

	categorylist = ArticleCategory.query.all()
	category = ArticleCategory.query.filter_by(id=actgid).first()

	pagination = data.Pagination(Article.query.filter_by(ctgid=actgid).order_by(Article.rldate.desc()), page, count)
	articles = pagination.items
	
	return render_template('spot-quotation.html', categorylist=categorylist, type=actgid, 
				articles=articles, activeid=activeid, pagination=pagination, count=count)

@main.route('/detail/<int:id>')
def detail(id):
	product = ProductInformation.query.filter_by(id=id).first()
	if not product:
		return redirect(request.args.get('next') or url_for('main.index'))
	return render_template('details.html', pd=product)

@main.route('/article/<int:id>')
def article(id):
	article = Article.query.filter_by(id=id).first()
	if not article:
		return redirect(url_for('main.spot_quotation'))
	article.hits += 1
	db_session.add(article)
	db_session.commit()
	return render_template('details-article.html', article=article)

app/templates/back-articles.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>文章列表</title>
    <link rel="stylesheet" href="/static/style/bootstrap.css">
    <link rel="stylesheet" href="/static/style/back.css">
    <link href="/static/style/back-common.css" rel="stylesheet">
</head>
<body>
      {% include 'util/admin/top.html' %}

      {% include 'util/admin/left-box.html' %}
	<div class="backArticleBox">
    <div class="backArticleName">文章列表</div>
		<table class="backArticleMenuBox" border="1">
			<tr>
				<td class="backArticleMenuNew"><a href="#"></a></td>
				<td class="backArticleMenuSave"><a href="#"></a></td>
				<td class="backArticleMenuSee"><a href="#"></a></td>
				<td class="backArticleMenuDelete"><a href="#"></a></td>
			</tr>
		</table>
		<div class="backArticleMenuOptions">
			<select name="cars" class="form-control">
				<option value="all">所有类别</option>
				<option value="option1">类别1</option>
				<option value="option2">类别2</option>
				<option value="option3">类别3</option>
			<div class="form-group">
    			<input type="text" class="form-control" placeholder="搜索文章">
    			<button class="btn btn-default">搜索</button>
    		</div>
		<div class="backArticleTable">
    	<div class="checkboxNormal">
      	<input type="checkbox">
      	<div class="checkboxID">ID</div>
      	<div class="checkboxTitle">标题</div>
      	<div class="checkboxType">类别</div>
      	<div class="checkboxOrigin">作者</div>
      	<div class="checkboxDate">日期</div>
      	<div class="checkboxOption">操作</div>
    	</div>
      {% for article in articles %}
    	<div class="checkboxNormal">
      	<input type="checkbox">
      	<div class="checkboxID">{{article.id}}</div>
      	<div class="checkboxTitle">{{article.title|article_title_filter}}</div>
      	<div class="checkboxType">{{article.category.name}}</div>
      	<div class="checkboxOrigin">{{article.author.username}}</div>
      	<div class="checkboxDate">{{format_datetime(article.rldate)}}</div>
      	<div class="checkboxOption">
      		<table border="1">
      			<tr>
      				<td><a class="checkboxOptionEdit" href="{{url_for('admin.modify_article', id=article.id)}}"></a></td>
      				<td><a class="checkboxOptionSee" href="{{url_for('main.article', id=article.id)}}"></a></td>
      				<td><a class="checkboxOptionDelete" href="#"></a></td>
      			</tr>
      		</table>
      	</div>
    	</div>
      {% endfor %}
    	<div class="stockButtonBox">
            <div class="stockButtons">
        <input type="button" class="stockButton stockButtonPre" {% if pagination.has_prev %}url="{{url_for('admin.article_list', page=pagination.page-1, count=count)}}"{% endif %}>
        {% for p in pagination.iter_pages() %}
          {% if p %}
            {% if p == pagination.page %}
            <input type="button" class="stockButton activeButton" disabled="disabled" url="{{url_for('admin.article_list', page=p,count=count)}}" value="{{p}}">
            {% else %}
            <input type="button" class="stockButton" url="{{ url_for('admin.article_list', page=p, count=count)}}" value="{{p}}">
            {% endif %}
            
          {% else %}
            <input type="button" class="stockButton" value="...">
          {% endif %}
        {% endfor %}
        <input type="button" class="stockButton stockButtonNext" {% if pagination.has_next %}url="{{url_for('admin.article_list', page=pagination.page+1,count=count)}}"{% endif %} value=" ">
            </div>
		</div>
		</div>
	</div>	
  <script src="/static/js/jquery.js"></script>
  <script src="/static/js/bootstrap.js"></script>
  <script src="/static/js/jquery.SuperSlide.2.1.1.js"></script>
  <script type="text/javascript" src="/static/js/paginationbutton.js"></script>
  <script type="text/javascript">
    $('.checkboxOptionDelete').click(function(){
      var issueID = $(this).parents('.checkboxOption').siblings('.checkboxID').text();
      $.ajax({
        type:'get',
        url : '/api/admin/delete/article/' + issueID,
        success : function(data) {
          alert('删除成功');
          window.location.reload();
        },
        error : function(){
          alert('通信出问题了'); 
        }
      });
    });
  </script>
</body>
</html>

app/templates/back-production.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>产品列表</title>
    <link rel="stylesheet" href="/static/style/bootstrap.css">
    <link rel="stylesheet" href="/static/style/back.css">
    <link href="/static/style/back-common.css" rel="stylesheet">
</head>
<body>
      {% include 'util/admin/top.html' %}

      {% include 'util/admin/left-box.html' %}
	<div class="backArticleBox">
    <div class="backArticleName">产品列表</div>
		<table class="backArticleMenuBox" border="1">
			<tr>
				<td class="backArticleMenuNew"><a href="#"></a></td>
				<td class="backArticleMenuSave"><a href="#"></a></td>
				<td class="backArticleMenuSee"><a href="#"></a></td>
				<td class="backArticleMenuDelete"><a href="#"></a></td>
			</tr>
		</table>
		<div class="backArticleMenuOptions">
			<select name="cars" class="form-control">
				<option value="all">所有类别</option>
				<option value="option1">类别1</option>
				<option value="option2">类别2</option>
				<option value="option3">类别3</option>
			<div class="form-group">
    			<input type="text" class="form-control" placeholder="搜索文章">
    			<button class="btn btn-default">搜索</button>
    		</div>
		<div class="backArticleTable">
    	<div class="checkboxNormal">
      	<input type="checkbox">
      	<div class="checkboxID">ID</div>
      	<div class="checkboxTitle">订单号</div>
      	<div class="checkboxType">类别</div>
      	<div class="checkboxOrigin">发布者</div>
      	<div class="checkboxDate">时间</div>
      	<div class="checkboxOption">操作</div>
    	</div>
      {% for p in product %}
      <div class="{% if p.id%2 == 1 %}checkboxDark{% else %}checkboxNormal{%endif%}">
        <input type="checkbox">
        <div class="checkboxID">{{p.id}}</div>
        <div class="checkboxTitle">{{p.ordnum}}</div>
        <div class="checkboxType">{{p.category.name}}</div>
        <div class="checkboxOrigin">{{p.user.username}}</div>
        <div class="checkboxDate">{{format_datetime(p.rldate)}}</div>
        <div class="checkboxOption">
          <table border="1">
            <tr>
              <td><a class="checkboxOptionEdit" href="{{url_for('admin.modify_product', id=p.id)}}"></a></td>
              <td><a class="checkboxOptionSee" href="{% if p.typeid == 1 %}{{url_for('main.detail', id=p.id)}}{% else %}{{url_for('main.purchase')}}{%endif%}"></a></td>
              <td><a class="checkboxOptionDelete" href="#"></a></td>
            </tr>
          </table>
        </div>
      </div>   
      {% endfor %}
    
    	
    	<div class="stockButtonBox">
            <div class="stockButtons">
        <input type="button" class="stockButton stockButtonPre" {% if pagination.has_prev %}url="{{url_for('admin.product_list', page=pagination.page-1, count=count)}}"{% endif %}>
        {% for p in pagination.iter_pages() %}
          {% if p %}
            {% if p == pagination.page %}
            <input type="button" class="stockButton activeButton" disabled="disabled" url="{{url_for('admin.product_list', page=p,count=count)}}" value="{{p}}">
            {% else %}
            <input type="button" class="stockButton" url="{{ url_for('admin.product_list', page=p, count=count)}}" value="{{p}}">
            {% endif %}
            
          {% else %}
            <input type="button" class="stockButton" value="...">
          {% endif %}
        {% endfor %}
        <input type="button" class="stockButton stockButtonNext" {% if pagination.has_next %}url="{{url_for('admin.product_list', page=pagination.page+1,count=count)}}"{% endif %} value=" ">
            </div>
		</div>
		</div>
	</div>	
  <script src="/static/js/jquery.js"></script>
  <script src="/static/js/bootstrap.js"></script>
  <script src="/static/js/jquery.SuperSlide.2.1.1.js"></script>
  <script type="text/javascript" src="/static/js/paginationbutton.js"></script>
    <script>
    $('.checkboxOptionDelete').click(function(){
      var pdtID = $(this).parents('.checkboxOption').siblings('.checkboxID').text();
      $.ajax({
        type:'get',
        url : '/api/admin/delete/product/' + pdtID,
        success : function(data) {
          alert('删除成功');
          window.location.reload();
        },
        error : function(){
          alert('通信出问题了'); 
        }
      });
    });
  </script>
</body>
</html>

app/templates/logistics.html
<html>
	<head>
		<title>logistics</title>
		<meta charset="utf-8">
		<link href="/static/style/logistics.css" rel="stylesheet">
	</head>
	<body>
		{% include 'util/main/header.html' %}
		<div class="main">
			
			<div class="map">
				<img src="/static/logistics/picture/hhh.jpg" id="big_img">

			</div>

			<div class="entrust">
				<div class="entrust-top">
					快速委托
				</div>
				<textarea id="entrust-content"></textarea>
				<div class="else-imformation">
						<p>公司名称</p>
						<input type="text" id="name">
						<p>手机</p>
						<input type="text" id="mobile">
						<p>联系人</p>
						<input type="text" id="linkman">
						<p>地区</p>
						<input type="text" id="area">
					<img id="submit" src="/static/logistics/picture/btn_01.png">
				</div>
			</div>

			<div class="order-record">
				<p>实施委托成交记录</p>
				<div class="order-menu">
					<p1>时间</p1><p2>详细内容</p2><p3>重量</p3>
				</div>
				<div class="order-menu order-content">
					<p1>11:11</p1><p2>熊**</p2><p3>130kg</p3>
				</div>
			</div>
			
		</div>
		{% include 'util/main/footer.html' %}
	</body>
</html>

app/templates/stock.html
<!DOCTYPE html>
<html>
<head>
	<title>现货资源</title>
	<meta charset="utf-8">
    <link rel="stylesheet" href="/static/style/bootstrap.css">
    <link rel="stylesheet" href="/static/style/back-stock.css">
    <link rel="stylesheet" href="/static/style/main.css">

</head>
<body>
	<div class="main">
	{% include 'util/main/header.html' %}
	<div class="Box">
		<div class="chooseTableButtonBox">
			<button class="chooseTableButton">收起筛选<img src="../static/back-stocks/picture/stock1.png"></button>
		</div>
		<table class="chooseTable" border="1">
			<tr>
				<td class="tableTittle">分类</td>
				<td class="tableBody" name="fenlei">
					<div class="tableBox">不限</div>
					{% for c in category %}
					<div class="tableBox" id="{{c.id}}">{{c.name}}</div>
					{% endfor %}
				</td>
			</tr>
			<tr>
				<td class="tableTittle">产地</td>
				<td class="tableBody" name="chandi">
					<div class="tableBox">不限</div>
					{% for key in producingArea %}
					<div class="tableBox" id="{{key}}">
					{{producingArea[key].getName()}}
					</div>

					{% endfor %}
				</td>
			</tr>
			<tr>
				<td class="tableTittle">交割地</td>
				<td class="tableBody" name="jiaogedi">
					<div class="tableBox">不限</div>
					{% for key in jiaogeArea %}
					<div class="tableBox" id="{{key}}">
					{{jiaogeArea[key]}}
					</div>
					{% endfor %}
				</td>
			</tr>
			<tr class="tableHigh">
				<td class="tableTittle">名企</td>
				<td class="tableBody" name="mingqi">
					<div class="tableBox">不限</div>
					<table border="1" class="tableBoxLogos">
						<tr>
							<td>LOGO</td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td class="tableTittle">低位发热量</td>
				<td class="tableBody" name="Qnet">
					<div class="tableBox">不限</div>
					{% for key in Qnet | dict_sorted %}
					<div class="tableBox" id="{{key}}">
					{{Qnet[key].getName()|setting_format}}
					</div>
					{% endfor %}
				</td>
			</tr>
			<tr>
				<td class="tableTittle">全硫份</td>
				<td class="tableBody" name="St">
					<div class="tableBox">不限</div>
					{% for key in St | dict_sorted %}
					<div class="tableBox" id="{{key}}">
					{{St[key].getName()|setting_format}}
					</div>
					{% endfor %}
				</td>
			</tr>
			<tr>
				<td class="tableTittle">挥发份</td>
				<td class="tableBody" name="V">
					<div class="tableBox">不限</div>
					{% for key in V | dict_sorted %}
					<div class="tableBox" id="{{key}}">
					{{V[key].getName()|setting_format}}
					</div>
					{% endfor %}
				</td>
			</tr>
			<tr>
				<td class="tableTittle">全水份</td>
				<td class="tableBody" name="Mt">
					<div class="tableBox">不限</div>
					{% for key in Mt | dict_sorted %}
					<div class="tableBox" id="{{key}}">
					{{Mt[key].getName()|setting_format}}
					</div>
					{% endfor %}
				</td>
			</tr>
		</table>
		<div class="More">更多</div>
			<table class="infoBox" border="1">
			<tr>
				<td class="infoMenuBox">
					<table border="1" class="infoMenuTable">
						<tr class="infoMenu">
							<td class="infoMenuMR"><a href="#">默认</a></td>
							<td class="infoMenuJG"><a href="#">价格</a></td>
							<td class="infoMenuKC"><a href="#">库存</a></td>
							<td class="infoMenuRQ"><a href="#">日期</a></td>
						</tr>
					</table>
					<a href="#" class="infoBoxJGD">交割地</a>
					<a href="#" class="infoBoxZDJ">最高价</a>
					<div class="infoBoxLine">—</div>
					<a href="#" class="infoBoxZGJ">最低价</a>
					<a href="#" class="infoBoxYXQ">有效期</a>
					<div class="infoBoxInfo">
						<div class="infoBoxGP">
							<div class="infoBoxGPPic"></div>
							今日挂牌总量:<span>123,456</span>吨
						</div>
						<div class="infoBoxTotal">共找到23,456条商品</div>
						<div class="infoBoxNow">{{pagination.page}}/{{pagination.total}}</div>
					</div>
					<button class="infoBoxR"></button>
					<button class="infoBoxL"></button>
				</td>
			</tr>
			<tr class="infoTittle">
				<td>
					<div class="stockClassification">分类</div>
					<div class="stockName">品名</div>
					<div class="stockCompany">供货公司</div>
					<div class="stockKAL">主指标</div>
					<div class="stockQuantity">库存（吨）</div>
					<div class="stockPrice">价格（元/吨）	</div>
					<div class="stockPlace">交割地</div>
					<div class="stockDate">有效期</div>
					<div class="stockOperation">操作</div>
				</td>
			</tr>
			{% for p in product %}
			<tr class="infoInner">
				<td>
					<div class="stockClassification">{{ p.category.name | string_filter}}</div>
					<div class="stockName">{{p.coal | string_filter}}</div>
					<div class="stockCompany">某公司名</div>
					<div class="stockKAL">{{p.industryIndex.qnetar|Qnet_filter}}Kcal</div>
					<div class="stockQuantity">{{p.stock|Qnet_filter}}</div>
					<div class="stockPrice">{{p.price}}</div>
					<div class="stockPlace">{{p.dpaddr|string_filter}}</div>
					<div class="stockDate">{{p.vldterm|string_filter}}</div>
					<a href="{{url_for('main.detail', id=p.id)}}"><div class="stockOperationButton"></div></a>
				</td>
			</tr>
			{% endfor %}
			
			<tr class="infoInner">
				<td>
					
				</td>
			</tr>
		</table>
		<div class="stockButtonBox">
			<div class="stockButtons">
				<input type="button" class="stockButton stockButtonPre" {% if pagination.has_prev %}url="{{url_for('main.stock', page=pagination.page-1, count=count,fenlei=fenlei_query_string, chandi=chandi_query_string, jiaogedi=jiaogedi_query_string, Qnet=Qnet_query_string, St=St_query_string, V=V_query_string, Mt=Mt_query_string)}}"{% endif %}>
				{% for p in pagination.iter_pages() %}
					{% if p %}
						{% if p == pagination.page %}
						<input type="button" class="stockButton activeButton" disabled="disabled" url="{{url_for('main.stock', page=p,count=count, fenlei=fenlei_query_string, chandi=chandi_query_string, jiaogedi=jiaogedi_query_string, Qnet=Qnet_query_string, St=St_query_string, V=V_query_string, Mt=Mt_query_string)}}" value="{{p}}">
						{% else %}
						<input type="button" class="stockButton" url="{{ url_for('main.stock', page=p, count=count,fenlei=fenlei_query_string, chandi=chandi_query_string, jiaogedi=jiaogedi_query_string, Qnet=Qnet_query_string, St=St_query_string, V=V_query_string, Mt=Mt_query_string)}}" value="{{p}}">
						{% endif %}
						
					{% else %}
						<input type="button" class="stockButton" value="...">
					{% endif %}
				{% endfor %}
				<input type="button" class="stockButton stockButtonNext" {% if pagination.has_next %}url="{{url_for('main.stock', page=pagination.page+1,count=count, fenlei=fenlei_query_string, chandi=chandi_query_string, jiaogedi=jiaogedi_query_string, Qnet=Qnet_query_string, St=St_query_string, V=V_query_string, Mt=Mt_query_string)}}"{% endif %} value=" ">
				
			</div>
		</div>
	</div>
		{% include '/util/main/footer.html' %}
	</div>
	  <script type="text/javascript">
	  	$('.chooseTable, .chooseTableButtonBox').fadeIn(200);
	  $('.chooseTableButton').click(function(){
  	  	$('.chooseTable, .chooseTableButtonBox').fadeOut(200);
	});
	$('.More').click(function(){
		$('.chooseTable, .chooseTableButtonBox').fadeIn(200);
	});
  </script>
  <script src="/static/js/jquery.js"></script>
  <script src="/static/js/bootstrap.js"></script>
  <script src="/static/js/jquery.SuperSlide.2.1.1.js"></script>
  <script type="text/javascript" src="/static/js/productselect.js"></script>
  <script type="text/javascript" src="/static/js/paginationbutton.js"></script>
</body>
</html>